/**:
  ros__parameters:
    # see data/calibration/realsense for details. todo: test by plotting until its clear
    angular_velocity_offset_x: 0.0000137881    # [rad/s]
    angular_velocity_offset_y: 0.0000415388362    # [rad/s]
    angular_velocity_offset_z: 0.000013439    # [rad/s]
#    angular_velocity_stddev_xx: 0.1  # 0.03  # [rad/s]
#    angular_velocity_stddev_yy: 0.1  # 0.03  # [rad/s]
#    angular_velocity_stddev_zz: 0.1  # 0.03  # [rad/s]
#    acceleration_stddev: 0.1  # 0.03  # [m/s^2]

    gyro_bias_threshold: 0.0  # [rad/s]
    timer_callback_interval_sec: 0.005  # [sec]
    straight_motion_ang_vel_upper_limit: 0.0  # [rad/s]. upper limit of yaw angular velocity, beyond which motion is not considered straight

#    base_link: "camera_link"