/**:
  ros__parameters:
    port: /dev/ttyUSB0
    frame_id: lidar  # should be overwritten by the launch file
    ignore_array: ""
    baudrate: 128000
    lidar_type: 1
    device_type: 0
    sample_rate: 5
    abnormal_check_count: 4
    fixed_resolution: true
    reversion: false  # todo: should this be true?
    inverted: true
    auto_reconnect: true
    isSingleChannel: false
    intensity: false
    support_motor_dtr: true
    angle_max: 180.0
    angle_min: -180.0
    range_max: 12.0  # this should be 10
    range_min: 0.1  # this should be 0.12
    frequency: 10.0
    invalid_range_is_inf: false
