publish_rate: 10.0
actors:
#  car_0:
#    initial_position: [0.8798897862434387, -1.6753101348876953, 0.3]
#    initial_orientation: -88.118721
#    velocity: [0.0, 0.0, 0.0]  # [0.2, 0.0, 0.0]
#    acceleration: [0.0, 0.0, 0.0]
#    size: [5.0, 3.0, 20.0]
  pedestrian_0:
    initial_position: [-2.1, -321.2, 0.30]
    velocity: [0.0, 0.0, 0.0]  # [0.05, 0.2, 0.0]
    acceleration: [0.0, 0.0, 0.0]
    angular_velocity: [0.0, 0.0, 0.0]  # [0.0, 0.0, 0.1]
    size: [1.0, 1.0, 10.7]
  car_1:
    initial_position: [ -1.2, -84.2, 0.3 ]
    initial_orientation: -89.43235779
    velocity: [ 0.0, 0.0, 0.0 ]  # [0.2, 0.0, 0.0]
    acceleration: [ 0.0, 0.0, 0.0 ]
    size: [ 10.0, 5.0, 20.0 ]
  car_2:
    initial_position: [ 2.1, -117.0, 0.3 ]
    initial_orientation: -89.43235779
    velocity: [ 0.0, 0.0, 0.0 ]  # [0.2, 0.0, 0.0]
    acceleration: [ 0.0, 0.0, 0.0 ]
    size: [ 3.0, 1.0, 20.0 ]
  car_3:
    initial_position: [ -1.2, -184.0, 0.3 ]
    initial_orientation: -89.43235779
    velocity: [ 0.0, 0.0, 0.0 ]  # [0.2, 0.0, 0.0]
    acceleration: [ 0.0, 0.0, 0.0 ]
    size: [ 3.0, 1.0, 20.0 ]
  pedestrian_1:
    initial_position: [ 10.0, -1.0, 0.0 ]
    velocity: [ 0.0, 0.0, 0.0 ]  # [0.05, 0.2, 0.0]
    acceleration: [ 0.0, 0.0, 0.0 ]
    angular_velocity: [ 0.0, 0.0, 0.0 ]  # [0.0, 0.0, 0.1]
    size: [ 0.5, 0.5, 10.7 ]
  cyclist_0:
    initial_position: [2.1, -184.0, 0.3]
    initial_orientation: -89.43235779
    velocity: [0.0, 0.0, 0.0]  # [0.1, 0.0, 0.0]
    acceleration: [0.0, 0.0, 0.0]
    size: [1.0, 0.3, 10.0]
  cyclist_1:
    initial_position: [ -1.2, -250.0, 0.3 ]
    initial_orientation: -89.43235779
    velocity: [ 0.0, 0.0, 0.0 ]  # [0.1, 0.0, 0.0]
    acceleration: [ 0.0, 0.0, 0.0 ]
    size: [ 1.0, 0.3, 10.0 ]
  generic_0:
    initial_position: [ 0.0, 0.0, 0.0 ]
    velocity: [ 0.0, 0.0, 0.0 ]  # [ 2.0, 0.5, 0.0 ]
    size: [ 0.5, 0.5, 10.5 ]
