publish_rate: 10.0
actors:
  car:
    count: 1
#    initial_position: [8.0, 0.0, 0.0]
    velocity: [0.0, 0.0, 0.0]  # [0.2, 0.0, 0.0]
#    acceleration: [0.0, 0.0, 0.0]
    size: [3.0, 1.0, 20.0]
  pedestrian:
    count: 1
#    initial_position: [10.0, -1.0, 0.0]
    velocity: [0.0, 0.0, 0.0]  # [0.05, 0.2, 0.0]
    acceleration: [0.0, 0.0, 0.0]
    angular_velocity: [0.0, 0.0, 0.0]  # [0.0, 0.0, 0.1]
    size: [0.5, 0.5, 10.7]
  cyclist:
    count: 3
#    initial_position: [10.0, -5.0, 0.0]
    velocity: [0.0, 0.0, 0.0]  # [0.1, 0.0, 0.0]
#    acceleration: [0.0, 0.0, 0.0]
    size: [1.0, 0.3, 10.0]
  generic:
    count: 0
#    initial_position: [ 0.0, 0.0, 0.0 ]
    velocity: [ 0.0, 0.0, 0.0 ]  # [ 2.0, 0.5, 0.0 ]
    size: [ 0.5, 0.5, 10.5 ]
